server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: dm-users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dm??serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:com/dm/mapper/*.xml
  type-aliases-package: com.dm
logging:
  level:
    com.dm: trace